name: vibers_net
description: A Video Streaming Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+3

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 
  unity_ads_plugin: ^0.3.7
  upi_india: ^3.0.1
  animated_text_kit: ^4.2.2
  audioplayers: ^6.1.0
  # facebook_audience_network: ^1.0.1
  flutter_facebook_auth: ^6.0.4
  
 
  chewie: ^1.7.4
  video_player: ^2.8.2
  subtitle_wrapper_package: ^2.1.1
  flutter_screenutil: ^5.9.3

  flutterwave_standard: ^1.0.6
  payu_web_checkout: ^1.0.3
  # payhere_mobilesdk_flutter: ^3.0.10 // TODO : UN COMMENT THIS PACKAGE
  file_picker: ^8.1.2
  flutter_localization: ^0.2.2
  flutter_translate: ^4.0.3
  loading_overlay: ^0.3.0
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  path_provider: ^2.1.4
  sticky_headers: ^0.3.0+2
  fluttertoast: ^8.2.1

  # Old Version but do not upgrade it.
  intro_slider: ^3.0.10

  image_picker: ^1.1.2
  cached_network_image: ^3.3.0
  sqflite: ^2.2.0+3
  syncfusion_flutter_pdfviewer: ^20.3.56
  
  flutter_cache_manager: ^3.3.0
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^5.0.0
 
  
  
  share_plus: ^10.0.2
  lottie: ^3.1.2

  launch_review: ^3.0.1
  page_transition: ^2.0.9

  # Old Version but do not upgrade it.
  flutter_downloader: ^1.8.0
  
  permission_handler: ^11.3.1
 
  font_awesome_flutter: ^10.1.1
  bubble_tab_indicator: ^0.1.6
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  google_sign_in: ^6.2.1
  flutter_braintree: ^4.0.0
  razorpay_flutter: ^1.3.5
  paytm: ^3.0.1
  # flutter_paystack: ^1.0.7 
  in_app_update: ^4.2.3
  dio: ^5.7.0
  flutter_inapp_purchase: ^5.4.0
  flutter_rating_bar: ^4.0.1
  dart_ipify: ^1.1.1
  connectivity_plus: ^5.0.2
  connectivity_plus_web: ^1.2.5
  onesignal_flutter: ^5.2.5
  intl: ^0.18.0
  pinput: ^5.0.0
  equatable: ^2.0.5


  # Old Versions but do not upgrade these.
  flutter_widget_from_html: ^0.9.1
  # flutter_widget_from_html: ^0.8.5
  just_audio: ^0.9.29

  firebase_messaging: ^15.1.2
  http_auth: ^1.0.1
  http: ^0.13.5
  flutter_credit_card: ^4.0.1
  firebase_analytics: ^11.3.3
  google_mobile_ads: ^2.3.0
  change_app_package_name: ^1.1.0
  flutter_lwa: ^2.0.0
  horizontal_data_table: ^4.1.2+2
  flutter_inappwebview: ^5.7.1
  # android_path_provider: ^2.2.10
  device_info_plus: ^10.1.2
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  collection: ^1.16.0
  fwfh_text_style: ^2.23.8
  wakelock_plus: ^1.1.4

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0
  webview_flutter: ^2.7.0
  http: ^1.1.0
  flutter_cashfree_pg_sdk: ^2.1.6+36



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/
    - icons/
    - assets/native_splash/
    - assets/launcher_ic/
    - assets/fonts/
    - assets/fonts/gothic_a1/
    - assets/animations/
    - assets/illstraions/

  fonts:
    - family: GothicA1
      fonts:
        - asset: assets/fonts/gothic_a1/GothicA1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/gothic_a1/GothicA1-Light.ttf
          weight: 300
        - asset: assets/fonts/gothic_a1/GothicA1-Regular.ttf
          weight: 400
        - asset: assets/fonts/gothic_a1/GothicA1-Medium.ttf
          weight: 500
        - asset: assets/fonts/gothic_a1/GothicA1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gothic_a1/GothicA1-Bold.ttf
          weight: 700
        - asset: assets/fonts/gothic_a1/GothicA1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/gothic_a1/GothicA1-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900